'use strict';
const data = JSON.parse(document.getElementById('site-data').textContent);
const $ = id => document.getElementById(id);
const fmt = (v, digits=1) => v == null ? '—' : Number(v).toLocaleString('en-US', {minimumFractionDigits:digits, maximumFractionDigits:digits});
const dateText = value => value ? new Date(value+'T12:00:00').toLocaleDateString('he-IL',{day:'numeric',month:'short',year:'numeric'}) : 'לא זמין';
const regimes = {NORMAL:'רגיל',WATCH:'מעקב',ELEVATED:'לחץ מוגבר',CRITICAL:'לחץ קריטי'};
const colors = ['#86caa0','#d3c28a','#d49a76','#cc8d90'];
const labels = {vix_5d:'שינוי בתנודתיות · 5 ימים',vix_20d:'שינוי בתנודתיות · 20 ימים',vix_level:'רמת התנודתיות',vol_of_vol:'תנודתיות של התנודתיות',realized_vol:'תנודתיות בפועל',vix_term:'מבנה עקום התנודתיות',vix_term_5d:'שינוי בעקום התנודתיות',vvix_ratio:'מחיר ההגנה על תנודתיות',vvix_level:'תנודתיות צפויה של VIX',off_high:'מרחק המדד מהשיא',below_50:'המדד מול ממוצע 50 יום',below_150:'המדד מול ממוצע 150 יום',below_200:'המדד מול ממוצע 200 יום',stretch:'מרחק מעל ממוצע 200 יום',narrow_20:'היחלשות רוחב השוק · 20 יום',narrow_60:'היחלשות רוחב השוק · 60 יום',narrow_trend:'מגמת רוחב השוק',rsp_off_high:'משקל שווה — מרחק מהשיא',rsp_below_200:'משקל שווה מול ממוצע 200 יום',divergence:'פער בין המדד למשקל שווה',rsp_vol_gap:'פער תנודתיות — משקל שווה',credit_20:'לחץ בשוק האשראי · 20 יום',credit_60:'לחץ בשוק האשראי · 60 יום',defensive:'רוטציה למגזרים הגנתיים',bonds_bid:'ביקוש לאג״ח ביחס למניות',xlp_slope:'מגמת הצריכה הבסיסית',xlu_ratio:'מגזר התשתיות מול השוק',risk_off_20:'ירידה בתיאבון לסיכון',risk_off_accel:'האצה בירידה בתיאבון לסיכון',curve_flat:'השתטחות עקום התשואות',curve_steepen_20:'התלילות בעקום התשואות',rates_up_20:'עליית תשואת האג״ח',bond_up_20:'עליית מחירי האג״ח',bond_stretch:'האג״ח מול המגמה הארוכה',yield_down_20:'ירידה בתשואת אג״ח ל־10 שנים',yield_low:'רמת תשואה נמוכה',short_rate_down_20:'ירידת הריבית הקצרה',long_yield_high:'רמת התשואה הארוכה',long_yield_up_20:'עלייה בתשואה הארוכה',term_premium:'פער תשואות 30–10 שנים',term_premium_20:'שינוי בפער התשואות',rut_off_high:'מניות קטנות — מרחק מהשיא',rut_below_200:'מניות קטנות מול ממוצע 200',rut_lag:'פיגור במניות קטנות',sox_off_high:'שבבים — מרחק מהשיא',sox_fade_60:'היחלשות מניות השבבים',djt_div:'פער בין תחבורה לתעשייה',gold_bid:'ביקוש לזהב',dollar_bid:'התחזקות הדולר',seasonal:'עונתיות היסטורית',breadth_thin_50:'השתתפות מעל ממוצע 50 יום',breadth_thin_200:'השתתפות מעל ממוצע 200 יום',breadth_euphoria:'השתתפות רחבה בשוק',breadth_rolling:'שינוי ברוחב השוק',breadth_rolling_200:'שינוי ברוחב השוק הארוך',breadth_divergence:'פער בין עליית המדד להשתתפות',breadth_nhnl:'פער שיאים ושפלים חדשים',puts_heavy:'ביקוש לאופציות מכר',puts_light:'ביקוש נמוך להגנות',puts_change_20:'שינוי ביחס אופציות מכר/רכש',debt_growth_60:'גידול בחוב · 60 יום',debt_growth_20:'גידול בחוב · 20 יום',debt_accel:'האצה בגידול החוב',debt_public_share:'חלק הציבור בחוב',pe_stretch:'מכפיל רווח השוק'};
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('version').textContent=data.version;
if(data.notice){$('notice').hidden=false;$('notice').textContent=data.notice;}
if(!data.live){$('refresh').hidden=true;$('analyze').hidden=true;}
if(data.reading){const r=data.reading;$('chance').textContent=fmt(r.chance);$('mss').textContent=fmt(r.mss);$('asof').textContent=dateText(r.date);$('regime').textContent=r.mss==null?'אין כיסוי מספיק':(regimes[r.regime]||r.regime);document.body.dataset.regime=r.regime;
  $('mss-change').textContent=`שינוי ב־5 מפגשים: ${r.change==null?'—':(r.change>0?'+':'')+fmt(r.change)}`;
  if(r.mss!=null){$('score-pointer').hidden=false;$('score-pointer').style.right=`${Math.max(0,Math.min(100,r.mss))}%`;}
  if(r.chance!=null){$('orbit').style.strokeDasharray=`${Math.max(0,Math.min(100,r.chance))*3.52} 352`;$('context-copy').textContent=`המודל מעריך הסתברות של ${fmt(r.chance)}% לאירוע שהוגדר. גם כאשר הלחץ עולה, הירידה אינה ודאית והמדד עשוי להתאושש בתוך התקופה.`;}
  if(data.baseline!=null){$('baseline').textContent=fmt(data.baseline)+'%';if(r.chance!=null&&data.baseline>0){const ratio=r.chance/data.baseline;$('relative').textContent=`פי ${fmt(ratio)} משיעור הבסיס`;}}
  const age=Math.floor((Date.now()-new Date(r.date+'T23:59:59').getTime())/86400000);
  if(age>4){$('notice').hidden=false;$('notice').textContent=`הקריאה האחרונה היא מ־${dateText(r.date)}. הנתונים אינם מעודכנים; יש לרענן לפני פירוש הקריאה.`;}
}
function spark(points){const p=points.filter(x=>x.value!=null);if(p.length<2)return '';const lo=Math.min(...p.map(x=>x.value)),hi=Math.max(...p.map(x=>x.value));const d=p.map((v,i)=>`${i?'L':'M'}${(i/(p.length-1)*80).toFixed(1)},${(28-(v.value-lo)/(hi-lo||1)*24).toFixed(1)}`).join(' ');return `<svg class="market-spark" viewBox="0 0 80 32" aria-hidden="true"><path d="${d}" fill="none" stroke="#86c89f" stroke-width="1.5"/></svg>`;}
const markets=data.markets.length?data.markets:[{title:'S&P 500'},{title:'VIX'},{title:'אג״ח ארה״ב ל־10 שנים'},{title:'Russell 2000'}];
$('markets').innerHTML=markets.map(m=>`<article class="market-card"><div class="market-title"><span>${escapeHTML(m.title)}</span><small>${m.date?escapeHTML(dateText(m.date)):'ממתין לנתונים'}</small></div><div class="market-value" dir="ltr">${fmt(m.value,2)}${m.key==='^TNX'&&m.value!=null?'%':''}</div><span class="market-change">${m.change==null?'לא זמין':(m.change>0?'+':'')+fmt(m.change,2)+'%'} <span class="muted">${m.change==null?'':'יומי'}</span></span>${spark(m.series||[])}</article>`).join('');
const factors=[...data.factors].sort((a,b)=>(b.value??-1)-(a.value??-1));let expanded=false;
function drawFactors(){const shown=expanded?factors:factors.slice(0,6);$('factor-count').textContent=factors.length?`${factors.filter(f=>f.value!=null).length} / ${factors.length} זמינים`:'ממתין לחישוב';$('factor-list').innerHTML=shown.length?shown.map(f=>`<div class="factor-row"><div class="factor-name">${escapeHTML(labels[f.key]||f.key)}<small>${escapeHTML(f.key)}</small></div><div class="factor-bar"><div class="factor-track"><span style="width:${Math.max(0,Math.min(100,f.value??0))}%;background:${f.value>=85?colors[3]:f.value>=70?colors[2]:f.value>=45?colors[1]:colors[0]}"></span></div><b dir="ltr">${fmt(f.value,0)}</b></div></div>`).join(''):'<div class="empty-box">הגורמים יופיעו לאחר חישוב המודל<span>רק גורמים שעברו את תנאי הבחירה נכללים בציון.</span></div>';$('show-factors').hidden=factors.length<=6;$('show-factors').textContent=expanded?'הצגת פחות גורמים ↑':`הצגת כל ${factors.length} הגורמים ↓`;}
$('show-factors').addEventListener('click',()=>{expanded=!expanded;drawFactors();});drawFactors();
$('evidence').innerHTML=data.evidence.length?data.evidence.map((e,i)=>`<div class="evidence-row"><div class="evidence-name" dir="ltr">${escapeHTML(e.band)}<small>${fmt(e.days,0)} ימים</small></div><div class="evidence-bar"><span style="width:${Math.max(0,Math.min(100,e.rate??0))}%;background:${colors[i]}"></span></div><b dir="ltr">${e.rate==null?'—':fmt(e.rate)+'%'}</b></div>`).join(''):'<div class="empty-box">טרם חושב בגרסה הנוכחית<span>הנתונים יוצגו לאחר חישוב ההיסטוריה מחדש.</span></div>';
let selectedSeries=data.history.chance.some(p=>p.value!=null)?'chance':'spx',range=63,currentPoints=[];
const chartNames={chance:'הסתברות לירידה',mss:'ציון לחץ השוק · MSS',spx:'S&P 500'};
const svgNS='http://www.w3.org/2000/svg';
function drawChart(){document.querySelectorAll('[data-series]').forEach(b=>{const on=b.dataset.series===selectedSeries;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});document.querySelectorAll('[data-range]').forEach(b=>{const on=Number(b.dataset.range)===range;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});$('series-label').textContent=chartNames[selectedSeries];const source=data.history[selectedSeries].slice(-range),valid=source.filter(p=>p.value!=null);$('chart-empty').hidden=valid.length>0;$('chart-tooltip').hidden=true;const chart=$('history-chart');chart.setAttribute('aria-label',`${chartNames[selectedSeries]} — ${range} מפגשים אחרונים`);
  const vals=valid.map(p=>p.value),mn=vals.length?Math.min(...vals):0,mx=vals.length?Math.max(...vals):100,pad=selectedSeries==='spx'?Math.max((mx-mn)*.15,mx*.002):5,lo=selectedSeries==='spx'?mn-pad:Math.max(0,mn-pad),hi=selectedSeries==='spx'?mx+pad:Math.min(100,Math.max(mx+pad,lo+10));const x=i=>58+i/Math.max(source.length-1,1)*921,y=v=>235-(v-lo)/(hi-lo||1)*213;
  let markup='<defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#8ce3ae" stop-opacity=".16"/><stop offset="100%" stop-color="#8ce3ae" stop-opacity="0"/></linearGradient></defs>';
  for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4,yy=y(v);markup+=`<line x1="58" x2="979" y1="${yy}" y2="${yy}" stroke="#2a3a2e" stroke-dasharray="3 6"/><text x="45" y="${yy+4}" text-anchor="end" fill="#8da290" font-size="12">${fmt(v,selectedSeries==='spx'?0:1)}${selectedSeries==='chance'?'%':''}</text>`;}
  let segments=[],segment=[];currentPoints=[];source.forEach((p,i)=>{if(p.value==null){if(segment.length)segments.push(segment);segment=[];return;}const point={x:x(i),y:y(p.value),...p};segment.push(point);currentPoints.push(point);});if(segment.length)segments.push(segment);
  segments.forEach(s=>{const path=s.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(2)},${p.y.toFixed(2)}`).join(' ');markup+=`<path d="${path} L${s.at(-1).x},235 L${s[0].x},235 Z" fill="url(#chart-fill)"/><path d="${path}" fill="none" stroke="#9aebba" stroke-width="2.2" stroke-linejoin="round"/>`;});
  if(valid.length){const last=currentPoints.at(-1);markup+=`<circle cx="${last.x}" cy="${last.y}" r="4" fill="#acfacb" stroke="#172a1e" stroke-width="2"/>`;const ticks=Math.min(5,source.length);for(let i=0;i<ticks;i++){const j=Math.round(i*(source.length-1)/Math.max(ticks-1,1));markup+=`<text x="${x(j)}" y="267" text-anchor="${i===0?'start':i===ticks-1?'end':'middle'}" fill="#8da290" font-size="12">${escapeHTML(source[j].date.slice(5))}</text>`;}$('chart-span').textContent=`${dateText(valid[0].date)} — ${dateText(valid.at(-1).date)}`;}else $('chart-span').textContent='אין נתונים לטווח הנבחר';
  markup+='<line id="crosshair" y1="20" y2="235" stroke="#b1d4ba" stroke-dasharray="3 4" visibility="hidden"/>';chart.innerHTML=markup;
  $('chart-note').textContent=selectedSeries==='spx'?'מחירי סגירה מתוך נתוני הפרויקט. אין כאן ציטוט תוך־יומי.':selectedSeries==='mss'?'ציון לחץ 0–100. הטווחים נקבעים על סולם זה, ולא על ההסתברות.':'חלונות החיזוי חופפים; קריאות סמוכות אינן תצפיות עצמאיות.';
}
document.querySelectorAll('[data-series]').forEach(b=>b.addEventListener('click',()=>{selectedSeries=b.dataset.series;drawChart();}));document.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',()=>{range=Number(b.dataset.range);drawChart();}));
$('history-chart').addEventListener('pointermove',event=>{if(!currentPoints.length)return;const svg=$('history-chart'),p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const loc=p.matrixTransform(svg.getScreenCTM().inverse());const near=currentPoints.reduce((a,b)=>Math.abs(a.x-loc.x)<Math.abs(b.x-loc.x)?a:b);const line=$('crosshair');line.setAttribute('x1',near.x);line.setAttribute('x2',near.x);line.setAttribute('visibility','visible');$('chart-tooltip').textContent=`${dateText(near.date)} · ${fmt(near.value,selectedSeries==='spx'?2:1)}${selectedSeries==='chance'?'%':''}`;$('chart-tooltip').hidden=false;});
$('history-chart').addEventListener('pointerleave',()=>{$('chart-tooltip').hidden=true;$('crosshair')?.setAttribute('visibility','hidden');});drawChart();
document.querySelectorAll('.sidebar nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.sidebar nav a').forEach(x=>x.classList.toggle('active',x===a));}));
let pollTimer=null,busy=false;
function jobMessage(text,error=false){$('job').hidden=false;$('job').textContent=text;$('job').classList.toggle('error',error);}
function lock(value){busy=value;$('refresh').disabled=value;$('analyze').disabled=value;}
async function status(){try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw new Error('status');const s=await r.json();if(s.running){lock(true);jobMessage('החישוב מתבצע. איסוף הנתונים עשוי להימשך מספר דקות.');pollTimer=setTimeout(status,2000);}else if(busy){lock(false);if(s.error)jobMessage('החישוב לא הושלם. הקריאה הקודמת נשמרה. אפשר לנסות שוב.',true);else location.reload();}}catch{lock(false);jobMessage('החיבור לשרת נותק. יש לבדוק שהשרת פועל ולנסות שוב.',true);}}
async function run(path){if(busy)return;lock(true);jobMessage(path==='/analyze'?'אוסף נתונים ומחשב מחדש את המודל…':'מרענן מחירים ומחשב את הקריאה…');try{const r=await fetch(path,{method:'POST'});if(!r.ok){if(r.status===409){jobMessage('כבר מתבצע חישוב. ממתין לסיום…');pollTimer=setTimeout(status,1500);return;}throw new Error('update');}if(r.status===202)pollTimer=setTimeout(status,1500);else location.reload();}catch{lock(false);jobMessage('לא ניתן להשלים את הרענון. הנתונים הקודמים נשמרו; אפשר לנסות שוב.',true);}}
$('refresh').addEventListener('click',()=>run('/refresh'));$('analyze').addEventListener('click',()=>run('/analyze'));if(data.live)status();
